### ISSUE TITLE
General code review request

### ISSUE THREAD

**Issue by aaomidi** [ipinfo/java#2]
Just take a quick look at the codebase, I'll be writing some unit tests for it too so we can ensure all of its components work properly.

Let me know if you have any design/maintainability questions :)

(Feel free to unassign yourself)

**Comment by pshevtsov** [comment]
I've found some Javadoc problems:

- [model/ASNResponse.java#L37](https://github.com/ipinfo/java/blob/master/src/main/java/io/ipinfo/api/model/ASNResponse.java#L37) `@param context` tag description is missing
- [IPInfo.java#L34](https://github.com/ipinfo/java/blob/master/src/main/java/io/ipinfo/api/IPInfo.java#L34) `@return` tag description is missing
- [IPInfo.java#L43](https://github.com/ipinfo/java/blob/master/src/main/java/io/ipinfo/api/IPInfo.java#L43) `@param ip` tag description is missing
- [IPInfo.java#L45](https://github.com/ipinfo/java/blob/master/src/main/java/io/ipinfo/api/IPInfo.java#L45) `throws` tag description is missing
- [IPInfo.java#L61](https://github.com/ipinfo/java/blob/master/src/main/java/io/ipinfo/api/IPInfo.java#L61) `@param asn` tag description is missing
- [IPInfo.java#L63](https://github.com/ipinfo/java/blob/master/src/main/java/io/ipinfo/api/IPInfo.java#L63) `throws` tag description is missing
- [model/IPResponse.java#L38](https://github.com/ipinfo/java/blob/master/src/main/java/io/ipinfo/api/model/IPResponse.java#L38) `@param context` tag description is missing

**Comment by aaomidi** [comment]
Thanks - will fix these.
