### ISSUE TITLE
Upgrade okhttp to 4.10.

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/java#32]
We use 3.9.0 which looks pretty old now and this may make some users not want to install the library if it takes on too old of a subdependency from their side.

**Comment by ruurtjan** [comment]
Could you mint a new release with this merge included? There's [a vulnerability](https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044) in the `okhttp` version that comes with the latest release of `ipinfo-api`.

**Comment by rm-Umar** [comment]
@ruurtjan just released the new version [`2.2.0`](https://github.com/ipinfo/java/releases/tag/ipinfo-api-2.2.0) Thank you for the contribution!

**Comment by ruurtjan** [comment]
Thank you 🙏
