### ISSUE TITLE
Guava version bump vulnerability

### ISSUE THREAD

**Issue by benlahav** [ipinfo/java#41]
Hi

You have a vulnerabilities from guava [here](https://mvnrepository.com/artifact/io.ipinfo/ipinfo-api/2.1.1).
You bot already created PR for this and has no conflicts, please merge and release new version.

Thank you!

Ben

**Comment by okohll** [comment]
Yes, please, +1

**Comment by abu-usama** [comment]
We released new version (2.2.1), and this is [fixed](https://github.com/ipinfo/java/pull/37). Thank you @okohll @benlahav
