### ISSUE TITLE
`IsCountry` and `isEU` not providing a response.

### ISSUE THREAD

**Issue by abdullahdevrel** [ipinfo/java#46]
Original discussion: https://twitter.com/steveofmcleod/status/1708796094598037917

> What's the best way to report a bug in IPinfo's  Java API? Screenshot shows the error.

![image](https://github.com/ipinfo/java/assets/111275753/3a64b1d7-1403-45b4-a746-bbd4647204ad)

> Error is caused by the block of code from io.ipinfo.api.IPinfo in this screenshot. It's not the right way to load the data when it is bundled in a JAR file.

![image](https://github.com/ipinfo/java/assets/111275753/dfe96dde-eedf-497d-b32c-2e8b1340ba8c)

**Comment by UmanShahzad** [comment]
We'll inline the files as static maps rather than doing this - bad idea to load files like that. We've hit similar issues in other environments like when using PyInstaller to build a single executable from Python code - the files don't get included.

**Comment by stevemcleod** [comment]
If I may leave a couple of suggestions,

First, in io.ipinfo.api.IPinfo, this block of code from lines 431 to 443 silently swallows errors:

```
  try {
                map = Collections.unmodifiableMap(gson.fromJson(new FileReader(countryFile), type));
                countriesFlags = Collections.unmodifiableMap(gson.fromJson(new FileReader(countryFlagFile), countriesFlagsType));
                countriesCurrencies = Collections.unmodifiableMap(gson.fromJson(new FileReader(countryCurrencyFile), countriesCurrencyType));
                continents = Collections.unmodifiableMap(gson.fromJson(new FileReader(continentFile), continentType));
                euList = Collections.unmodifiableList(gson.fromJson(new FileReader(euCountryFile), euCountriesType));
            } catch (Exception e) {
                map = Collections.unmodifiableMap(new HashMap<>());
                countriesFlags = Collections.unmodifiableMap(new HashMap<>());
                countriesCurrencies = Collections.unmodifiableMap(new HashMap<>());
                continents = Collections.unmodifiableMap(new HashMap<>());
                euList = Collections.unmodifiableList(new ArrayList<>());
            }
```

I suggest that the catch clause should wrap the exception in a RuntimeException and rethrow it:

```
            } catch (Exception e) {
                throw new RuntimeException("Unable to build IPinfo object", e);
            }
```

Using this "fail-fast" approach, the issue with the IPinfo object not building itself correctly would have become apparent immediately. It doesn't fix the underlying problem, but it reveals it much sooner.

**Comment by stevemcleod** [comment]
Suggestion 2:

@UmanShahzad mentioned changing the approach to load the data, which sounds sensible.

However, if you do want to keep the data in separate files, the Guava dependency you are already using offers a way to load text files into String objects. This approach should work both in a development environment, and in JAR files you distribute:

Here's a working example:
```
    public static void main(String[] args) {
        try {
            URL resource = com.google.common.io.Resources.getResource("en_US.json");
            String fileContents = com.google.common.io.Resources.toString(resource, StandardCharsets.UTF_8);
            System.out.println("fileContents = " + fileContents);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

You might need to adjust your dev environment's config a little, but in principle, this will work.

**Comment by UmanShahzad** [comment]
Yeah all complexities and failure cases around this that you mentioned @stevemcleod go away when we inline the data as static maps. Likely even optimized by the compiler so no map-loading is needed at runtime.

These are really tiny datasets, so there was never really a good reason to make them files in the first place. Apologies for the inconvenience around  that.

**Comment by UmanShahzad** [comment]
@stevemcleod can you try 3.0.0 now? Eager to know if the situation is solved now in your project.

**Comment by stevemcleod** [comment]
> @stevemcleod can you try 3.0.0 now? Eager to know if the situation is solved now in your project.

Yes, this version seems to work for me now.

**Comment by UmanShahzad** [comment]
Excellent thanks!
