### ISSUE TITLE
Get null for ip address

### ISSUE THREAD

**Issue by LiMengyang990726** [ipinfo/java#7]
I got `null` for my ip address.
```
IPInfo ipInfo = IPInfo.builder().setToken("<redacted>").build();
    String ipAddress = request.getRemoteAddr();
    try {
      IPResponse ipResponse = ipInfo.lookupIP(ipAddress);
      // Print out the hostname
      System.out.println("Testing starts here");
      System.out.println(ipAddress);
      System.out.println(ipResponse);
      System.out.println(ipResponse.getCountryName());
      System.out.println(ipResponse.getHostname());

      UserLocation userLocation = new UserLocation(user, ipResponse.getCountryName());
      datastore.storeLocation(userLocation);

    } catch (RateLimitedException ex) {
      System.out.println("Exceed rate limit");
    }
```

I have deployed it.

**Comment by UmanShahzad** [comment]
@LiMengyang990726 Probably need a bit more info. What does `request.getRemoteAddr()` return for the particular time you get `null`?

**Comment by LiMengyang990726** [comment]
Thank you so much for help me protect my token. And I have kinda solved the question.

1. `request.getRemoteAddr()` return the right format of ip address. E.g. 8.8.8.8
2. I have changed the `UserLocation userLocation = new UserLocation(user, ipResponse.getCountryName());` to `UserLocation userLocation = new UserLocation(user, ipResponse.getCountryCode());`. And it works perfectly.
3. If still want `getCountryName()`, add an additional country-code-to-name json file will do.

This service is great! A gentle reminder is that you are not able to test this in your development environment (meaning `localhost`, as it always return `127.0.0.1`), you can only test it after you deployed it.
