### ISSUE TITLE
"kotlin" repo?

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/java#8]
Is it possible in GitHub to make a dummy "kotlin" repo that basically points to this? Kotlin devs probably know to look here anyway, but it'd be nice to have the name there.

**Comment by UmanShahzad** [comment]
Looks like a repo redirect isn't possible unless you had previously renamed a repo, I think.

So we can probably just create a mini repo that has a README.md pointing to this.

**Comment by aaomidi** [comment]
Why? Kotlin devs are still going to use maven central which points here.

**Comment by UmanShahzad** [comment]
Right, nevermind.
