### ISSUE TITLE
Convert to Kotlin

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/java#9]
I think it'd be nice to get the codebase to be Kotlin rather than Java. With the auto-converter tool we can have a nice starting point in 5 minutes.

Can also use this opportunity to **document** how to use the library in Kotlin as well as Java.

**Comment by aaomidi** [comment]
But why? Java isn't going anywhere. I feel like it's not the best idea to just jump on new languages like that. We can have a seperate kotlin library.

Java is still extremely more mature and popular than Kotlin. Even understanding the fact that they're both interop to an extent, Kotlin limits us.

https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html

**Comment by UmanShahzad** [comment]
Not looking for a language war; it's just about using a much easier to work with language, for all the same VM benefits. It's not 'new' in a bad sense - it's supported by big orgs (JetBrains, Google), increasingly becoming the standard on Android, etc. Best of all it can be auto-converted to.

I don't think interop is an issue; even https://github.com/square/okhttp is converting to Kotlin, which is used by a very large number of people in Java. Currently they're about 50% of the way there. We're actually using them in this lib it seems :p

I'll also just drop [okhttp's issue about it](https://github.com/square/okhttp/issues/4723) here - do read it!

Anyway obviously not top priority.

**Comment by UmanShahzad** [comment]
OK so closing this because if we use Kotlin we'd probably use their coroutines implementation along with its runtime, which won't play well when trying to call it in Java code. So we'll need a separate Kotlin repo for this.

Kotlin users can still use the Java library in the meantime just fine.
